# -*- coding: utf-8 -*-
"""Germany_GDP_Forecast

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uH5cAavK6A2MbhslNFpjU9GGJOc2NPM9
"""

import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

# Read data from excel file
data = pd.read_excel("/content/sample_data/Germany.xlsx")

# Selecting the data for ARIMA model
germany_gdp = data[['Year', 'GDP']]
germany_gdp.set_index('Year', inplace=True)

# Fit the ARIMA model
model = ARIMA(germany_gdp, order=(5,1,0))
model_fit = model.fit()

# Forecasting for the next 5 years
forecast = model_fit.forecast(steps=5)

# Plotting the forecast
plt.figure(figsize=(10, 6))
plt.plot(germany_gdp.index, germany_gdp['GDP'], label='Historical GDP')
plt.plot(range(2023, 2028), forecast, color='red', linestyle='--', label='Forecasted GDP')
plt.title('Germany GDP Forecast 2023-2027')
plt.xlabel('Year')
plt.ylabel('GDP in Billion USD')
plt.legend()
plt.show()

# Output the forecast values
print('Forecasted GDP values for 2023 to 2027 in Billion USD :\n',forecast)